### ISSUE TITLE
Is it just me, or is building broken?

### ISSUE THREAD

**Issue by DRACL10N** [rojo-rbx/vscode-rojo#30] opened 2020-06-03 17:13 UTC
So, Rojo can't build to .rbxl, I get that. But is there an option to choose the build type? I haven't been able to find it, and so took it upon myself to pry open the code of the extension and solve it. I changed 1 character and now it works. Am I missing something or is this the only to solve this issue?

In V05.js, I changed:
"const outputFile = `${outputConfig}.${this.isConfigRootDataModel() ? "rbxl" : "rbxm"}`;"
to
"const outputFile = `${outputConfig}.${this.isConfigRootDataModel() ? "rbxlx" : "rbxm"}`;"

**Comment by evaera** [comment] 2020-06-03 18:25
Duplicate of #23

**Closed by evaera** 2020-06-03 18:25 UTC
